import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-900 h-screen max-w-screen overflow-hidden flex flex-col `}
        >
        <header className="h-12 w-full bg-slate-500">HEADER</header>
        <main className="flex-1 w-screen overflow-y-scroll">
          {children}
        </main>  
        <footer className="h-7 w-full bg-slate-500">footer</footer>
      </body>
    </html>
  );
}
